name: Java CI with Gradle + JaCoCo

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create .env file
        run: echo "$ENV_FILE" | tr '\\n' '\n' > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Verify .env file content
        run: cat .env

      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests & Generate Coverage Report
        run: ./gradlew test jacocoTestReport

      - name: Upload Coverage Report Artifact (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: build/reports/jacoco/test/html

      - name: Upload XML Report (for coverage tools)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml
          path: build/reports/jacoco/test/jacocoTestReport.xml
